all:
	g++ -o2 -o main.app main.cpp mathplot.cpp connectargsdlg.cpp serialport.cpp enumserial.cpp FIR.cpp polynomial_regression.cpp adaptive_algorithm.cpp `wx-config --cxxflags --libs` --std=c++11 -m64 -D _MAC_
	./main.app
